"""Emit the LaTeX result tables straight from the result CSVs.

Tables are generated rather than typed so that the numbers in the manuscript cannot drift from
the numbers in results/. AJS rule C2.tables requires real LaTeX tables (no screenshots), and
booktabs is used for rules.

Writes into manuscript/:
    tab_mase.tex     mean MASE by cell and method, winner in bold
    tab_mape.tex     the MAPE appendix table, showing where it is undefined
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results"
MAN = ROOT / "manuscript"

_s = importlib.util.spec_from_file_location("dgp", ROOT / "code" / "01_dgp.py")
dgp = importlib.util.module_from_spec(_s); _s.loader.exec_module(dgp)

ORDER = ["SeasonalNaive", "Theta", "AutoETS", "AutoARIMA", "Combination", "TimesFM3"]
HEAD = ["Seas.\\ naive", "Theta", "AutoETS", "AutoARIMA", "Combin.", "\\textbf{TimesFM-3}"]


def fmt(x: float, best: bool) -> str:
    if not np.isfinite(x):
        return "---"
    s = f"{x:.3f}"
    return f"\\textbf{{{s}}}" if best else s


def table_mase() -> None:
    m = pd.read_csv(RES / "table_mase.csv")
    m = m[m.horizon_slice == "h1_12"]
    piv = m.pivot_table(index=["dgp", "n"], columns="method", values="mean_MASE")[ORDER]

    # AJS requires table captions ABOVE the table, so the caption is emitted before the
    # tabular, not after it. See the journal's guidelines: "captions, above tables and below
    # graphics (figures)".
    lines = [
        "% generated by code/09_make_tables.py -- do not edit by hand",
        "\\begin{table}[p]", "\\centering",
        "\\caption{Mean MASE over $h = 1,\\dots,12$ across 200 replications per cell. Lower is "
        "better; the best method in each row is in bold. The parenthesised family after each "
        "DGP label is the one correctly specified for it by construction.}",
        "\\label{tab:mase}",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",  # keeps the 8-column table inside the text block
        "\\begin{tabular}{llrrrrrr}", "\\toprule",
        "DGP & $n$ & " + " & ".join(HEAD) + " \\\\", "\\midrule",
    ]
    prev = None
    for (d, n), row in piv.iterrows():
        best = row.idxmin()
        label = ""
        if d != prev:
            if prev is not None:
                lines.append("\\addlinespace")
            label = f"{d} ({dgp.CORRECT_MODEL[d]})"
            prev = d
        cells = " & ".join(fmt(row[c], c == best) for c in ORDER)
        lines.append(f"{label} & {n} & {cells} \\\\")
    lines += [
        "\\bottomrule", "\\end{tabular}",
        "\\caption{Mean MASE over $h = 1,\\dots,12$ across 200 replications per cell. Lower is "
        "better; the best method in each row is in bold. The parenthesised family after each "
        "DGP label is the one correctly specified for it by construction.}",
        "\\label{tab:mase}", "\\end{table}",
    ]
    (MAN / "tab_mase.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote manuscript/tab_mase.tex")


def table_mape() -> None:
    df = pd.read_csv(RES / "all_metrics.csv")
    d = df[df.horizon_slice == "h1_12"]
    piv = d.pivot_table(index="dgp", columns="method", values="MAPE", aggfunc="mean")[ORDER]
    # A DGP on which MAPE is ALWAYS undefined is dropped by pivot_table. Reindex so it appears
    # as a row of dashes: the reader must see the regime disappear, not find it missing.
    piv = piv.reindex(dgp.DGP_IDS)
    undef = d.groupby("dgp")["MAPE"].apply(lambda s: 100 * s.isna().mean()).reindex(dgp.DGP_IDS)

    lines = [
        "% generated by code/09_make_tables.py -- do not edit by hand",
        "\\begin{table}[t!]", "\\centering", "\\small",
        "\\begin{tabular}{lrrrrrrr}", "\\toprule",
        "DGP & \\% undefined & " + " & ".join(HEAD) + " \\\\", "\\midrule",
    ]
    for d_id, row in piv.iterrows():
        vals = row.dropna()
        best = vals.idxmin() if len(vals) else None
        cells = " & ".join(fmt(row[c], c == best) for c in ORDER)
        lines.append(f"{d_id} & {undef[d_id]:.0f}\\% & {cells} \\\\")
    lines += [
        "\\bottomrule", "\\end{tabular}",
        "\\caption{Mean MAPE over $h = 1,\\dots,12$, with the percentage of series on which "
        "MAPE is undefined. On the intermittent process D8 every series contains a zero, so "
        "MAPE cannot be computed at all and the entire regime in which TimesFM-3 wins most "
        "decisively disappears from the comparison.}",
        "\\label{tab:mape}", "\\end{table}",
    ]
    (MAN / "tab_mape.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote manuscript/tab_mape.tex")


def table_robustness() -> None:
    """Each method's accuracy relative to the best method in the same cell.

    This is the statistic that supports the robustness claim. Absolute worst-case MASE does
    NOT support it -- D3 is hard for every method, so absolute worst cases are dominated by
    that process rather than by any method's fragility. The ratio to the best method in the
    same cell isolates fragility, which is what "degrades gracefully" actually means.
    """
    m = pd.read_csv(RES / "table_mase.csv")
    m = m[m.horizon_slice == "h1_12"]
    piv = m.pivot_table(index=["dgp", "n"], columns="method", values="mean_MASE")
    ratio = piv.div(piv.min(axis=1), axis=0)

    stats = pd.DataFrame({
        "median": ratio.median(), "mean": ratio.mean(), "worst": ratio.max(),
        "worst_cell": [f"{d} $n={n}$" for d, n in
                       (ratio.idxmax()[c] for c in ratio.columns)],
    }).reindex(ORDER)

    lines = [
        "% generated by code/09_make_tables.py -- do not edit by hand",
        "\\begin{table}[t!]", "\\centering", "\\begin{tabular}{lrrrl}", "\\toprule",
        "Method & Median & Mean & Worst & Worst cell \\\\", "\\midrule",
    ]
    for meth, row in stats.iterrows():
        name = "\\textbf{TimesFM-3}" if meth == "TimesFM3" else meth
        b = "\\textbf{{{}}}".format if meth == "TimesFM3" else (lambda s: s)
        lines.append(f"{name} & {b(f'{row['median']:.3f}')} & {b(f'{row['mean']:.3f}')} & "
                     f"{b(f'{row['worst']:.2f}')} & {row['worst_cell']} \\\\")
    lines += [
        "\\bottomrule", "\\end{tabular}",
        "\\caption{Each method's mean MASE divided by the best mean MASE in the same cell, "
        "summarised over the 36 cells. A value of 1.00 means the method was the best in that "
        "cell. TimesFM-3 is never worse than $1.31\\times$ the best method anywhere, and in the "
        "median cell it is within 0.8\\% of it; every classical method is at least "
        "$2.2\\times$ worse somewhere.}",
        "\\label{tab:robust}", "\\end{table}",
    ]
    (MAN / "tab_robust.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote manuscript/tab_robust.tex")


def table_d8_metrics() -> None:
    """All four pre-registered point metrics plus the pinball loss, on the intermittent DGP.

    The metrics disagree sharply here and the disagreement is the finding, so it is tabulated
    rather than summarised. Reporting MASE alone -- the metric most favourable to TimesFM-3 --
    would be selective reporting of a pre-registered metric set.
    """
    m = pd.read_csv(RES / "table_mase.csv")
    m = m[(m.horizon_slice == "h1_12") & (m.dgp == "D8")]
    metrics = [("mean_MASE", "MASE"), ("mean_RMSSE", "RMSSE"),
               ("mean_sMAPE", "sMAPE"), ("mean_SPL", "Pinball")]

    lines = [
        "% generated by code/09_make_tables.py -- do not edit by hand",
        "\\begin{table}[t!]", "\\centering",
        "\\caption{The four scale-free metrics disagree on the intermittent process D8. MASE and "
        "the scaled pinball loss favour TimesFM-3 at every length; RMSSE and sMAPE favour the "
        "classical methods at every length. The best value in each row is in bold.}",
        "\\label{tab:d8metrics}",
        "\\small", "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{llrrrrrr}", "\\toprule",
        "Metric & $n$ & " + " & ".join(HEAD) + " \\\\", "\\midrule",
    ]
    for col, label in metrics:
        piv = m.pivot_table(index="n", columns="method", values=col)[ORDER]
        for i, (n, row) in enumerate(piv.iterrows()):
            best = row.idxmin()
            cells = " & ".join(fmt(row[c], c == best) for c in ORDER)
            lines.append(f"{label if i == 0 else ''} & {n} & {cells} \\\\")
        lines.append("\\addlinespace")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (MAN / "tab_d8metrics.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote manuscript/tab_d8metrics.tex")


def enforce_caption_above() -> None:
    """Guarantee every generated table puts its caption above the tabular (AJS rule).

    Rather than rely on each generator function emitting the caption in the right place --
    which regressed once already -- the placement is enforced here as the last step, by
    reusing the same transformation applied to the hand-written tables.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "fixcap", Path(__file__).resolve().parent / "91_fix_caption_placement.py")
    fixcap = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(fixcap)
    fixcap.main()


if __name__ == "__main__":
    table_mase()
    table_mape()
    table_robustness()
    table_d8_metrics()
    enforce_caption_above()
