"""JoF revision: bring the manuscript in line with every claim of the response to referees."""

from pathlib import Path

P = Path(__file__).resolve().parent.parent / "manuscript_jof" / "timesfm_jof.tex"

EDITS = [
    # R3-m7: the black-box caveat once in full (Introduction); here only the reproducibility point
    ("R3-m7", r"""TimesFM-3 is a black box in the sense that matters for interpretation, though not in the sense
that matters for reproducibility. Its weights, architecture and inference code are public, so every
forecast in this study can be reproduced exactly by any reader, and the checkpoint is fixed, so the
results do not depend on a service that may change. What is not available is the pre-training
corpus itself and any interpretation of the 330 million parameters comparable to the coefficients
of an ARIMA model. The study therefore treats TimesFM-3 as a
forecasting procedure whose properties are to be \emph{measured}, in the same way that a
forecaster evaluates any method whose internal workings cannot be inspected: by its accuracy
and calibration on data whose generating mechanism is known. This is the purpose of the
controlled design in \sectionref{sec:design} and of the robustness study in
\sectionref{sec:robustness}. Such measurements describe the model's behaviour; they do not
reveal the mechanism that produces it.""",
     r"""TimesFM-3 is a black box for interpretation (\sectionref{sec:intro}) but not for
reproducibility: its weights, architecture and inference code are public and the checkpoint is
fixed, so every forecast in this study can be regenerated by any reader
(\sectionref{sec:repro})."""),
    ("S5-S6", r"""errors (Supporting Information, Table~S5).""",
     r"""errors (Supporting Information, Tables~S5 and~S6)."""),
    # R3-M8: fine-tuning out of scope, with the reason
    ("R3-M8", r"""simulated processes are univariate by construction. A study exercising cross-series information
could reach different conclusions, and would be the natural sequel.""",
     r"""simulated processes are univariate by construction. A study exercising cross-series information
could reach different conclusions, and would be the natural sequel. Fine-tuning was also left out:
fine-tuning on a single series of 24 to 200 observations is not meaningful for a model of this size,
and fine-tuning on series from the data-generating processes would remove the separation between
the model and the test data on which the design rests."""),
    # R2-M4b: one factor at a time
    ("R2-M4b", r"""frequencies, outside the regions studied. Coverage in four features is also a necessary rather than a sufficient condition for
similarity, since two series can share these features and differ in others.""",
     r"""frequencies, outside the regions studied. Coverage in four features is also a necessary rather than a sufficient condition for
similarity, since two series can share these features and differ in others. And the departures from
the assumptions were applied one at a time, so their interactions, such as heavy tails combined with
an estimated period, were not examined."""),
]


def main():
    s = P.read_text(encoding="utf-8")
    for tag, old, new in EDITS:
        n = s.count(old)
        if n == 1:
            s = s.replace(old, new)
            print(f"{tag}: applied")
        elif new in s:
            print(f"{tag}: already applied")
        else:
            raise SystemExit(f"{tag}: {n} matches")
    P.write_text(s, encoding="utf-8")


if __name__ == "__main__":
    main()
