"""Structural revision after the editorial review (author: "do all you recommend").

New outline: 1 Introduction (with contributions) / 2 TimesFM-3 / 3 Design (+3.4 protocol and hypotheses)
/ 4 Pre-registered comparison (+4.6 hypotheses table) / 5 Post-hoc analyses of the simulation / 6 M4
(representativeness moved here) / 7 Discussion (summary-of-findings table, practical considerations with
cost and licence, threats to validity) / 8 Conclusion / 9 Computational details.

The new body is code/K11_body.tex; the DGP table and the reproducibility paragraph are carried over verbatim
from the current manuscript. Table 3 (win counts) is replaced by counts in the forest-plot panels; the
fifteen-method table moves to the Supporting Information (Table S10) and a scatter plot takes its place.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
P = ROOT / "manuscript_jof" / "timesfm_jof.tex"
BODY = ROOT / "code" / "K11_body.tex"


def between(s, start, end, include_end=False):
    a = s.index(start)
    b = s.index(end, a) + (len(end) if include_end else 0)
    return s[a:b]


def main():
    s = P.read_text(encoding="utf-8")
    body = BODY.read_text(encoding="utf-8")
    dgp_start = s.index("\\begin{table}", s.index("\\subsection{Data-generating processes}"))
    dgptable = s[dgp_start:s.index("\\end{table}", dgp_start) + len("\\end{table}")]
    assert "tab:dgps" in dgptable
    repro = between(s, "All results were produced with", "\\section*{Acknowledgements}").rstrip() + "\n"
    body = body.replace("DGPTABLE", dgptable).replace("REPRO", repro)

    a = s.index("\\section{Introduction}")
    b = s.index("\\section*{Acknowledgements}")
    s = s[:a] + body + "\n" + s[b:]

    old = s[s.index("\\section*{Data availability statement}"):s.index("\\section*{Author e-mail addresses}")]
    new = ("\\section*{Data availability statement}\n"
           "The complete research compendium is archived on Zenodo, "
           "\\url{https://doi.org/10.5281/zenodo.22681072} (concept DOI, resolving to all versions), and "
           "mirrored at \\url{https://github.com/ebrahimkhaled/timesfm-classical-paper}: the pre-registered "
           "protocol, the deviation log, the entire pipeline, the per-series metrics, the raw forecasts and "
           "quantiles, every figure and the manuscript source. The simulation data are generated by that code "
           "from documented seeds; the real-data tier uses the publicly available M4 competition data "
           "\\citep{makridakis2020m4}, which the code re-fetches, with the seeded 1\\,000-series sample included. "
           "The raw forecasts are deposited so that they can be re-scored under other losses. TimesFM-3's "
           "weights are not redistributed; the code downloads them from Hugging Face.\n\n")
    s = s.replace(old, new)

    for gone in ["sec:operational", "sec:extended", "sec:robustness}", "sec:recommendations", "sec:cost",
                 "sec:licence", "sec:tfm-check", "tab:opponents", "tab:extended}", "DGPTABLE", "REPRO\n"]:
        assert gone not in s, gone
    P.write_text(s, encoding="utf-8")
    print("restructured")


if __name__ == "__main__":
    main()
